# Auto-generated by structural-computing-bench. Do not edit by hand.
# To regenerate: `python scripts/run_calibration.py --out <path>`.

CALIBRATED_COSTS = {
    ('T0', 'count_solutions'): {'model': 'exponential', 'params': (8.3564940316913e-05, 0.08233733998316162), 'rms': 0.2761758261573101},
    ('T2', 'matchgate_rank'): {'model': 'power_law', 'params': (0.00125776307757691, 3.271882171031816), 'rms': 0.17498049325684853},
    ('T2', 'matching_count'): {'model': 'exponential', 'params': (0.0005396949697126797, 0.1316127928935648), 'rms': 0.23326350747692826},
    ('T4', 'matching_count'): {'model': 'exponential', 'params': (0.0002926088347245634, 0.060097683600376206), 'rms': 0.7036577152844701},
}

METADATA = {'generated_at': '2026-05-31T13:53:11+00:00', 'machine': 'AMD64-Windows-11', 'python': '3.13.13', 'bench_version': '0.1.0a1'}
